### ISSUE TITLE
Apply a Drop cap on PLText?

### ISSUE THREAD

**Issue by okgint** [phax/ph-pdf-layout#1]
I want to add a drop cap feature on PLText,
My solution was to copy-and-paste PLText ( I renamed it as PLTextModification)
and I did modifications on methods: onPrepare() & onPerform().

It worked, but it was a horrible hack...

My question : Are there any ways to add drop cap feature on PLText ?

**Comment by phax** [comment]
Hi there!
This is definitively a tricky one :)

I have some short questions on drop caps as I never thought about this:
  * How many lines are the supposed to span?
  * Is it always one letter or can it be more?

Maybe you provide me with a link how you want it to look :)

Thanks, Philip
