### ISSUE TITLE
Wrong linespacing in the end of page

### ISSUE THREAD

**Issue by RangerMak** [phax/ph-pdf-layout#10]
Sometimes last line of page in multiline text can be rendered using wrong linespace.
Examlpe: https://ibb.co/FWNRYbD

This text was added to document using code
```
pagesSet.addElement(new PLText(loremRus, italicBoldFont12).setLineSpacing(1.5f));
```
Last line was rendened with wrong linespace for fitting it into page.
Another lines of text was rendered with correct linespace.

The result document looks strange in this case.

**Comment by phax** [comment]
That occurred only on line break.
