### ISSUE TITLE
Empty space when adding headers with different height

### ISSUE THREAD

**Issue by Sasan-Yavari** [phax/ph-pdf-layout#14]
When we add a header to the first page with `173.78516` height and add another header to other pages with `40.0` height, it reserves `173.78516` for all the headers and in the pages, we see empty space under the smaller header.

This is the message:
`PageSet margin top was changed from 40.0 to 173.78516 so that firstPageHeader fits!`

**Comment by phax** [comment]
Part of 5.1.2 release
