### ISSUE TITLE
How to keep a table together?

### ISSUE THREAD

**Issue by sventschui** [phax/ph-pdf-layout#15]
I have a PDF with multiple tables. For the page break one of these tables is torn apart. Is there a possibility to move the entire table to a new page instead of only some of its rows?

**Comment by phax** [comment]
Did you try adding a `new PLPageBreak()` before the table?

**Comment by sventschui** [comment]
Wrapping the tables in another table with each cell set to `PLTableCell.setVertSplittable(false)` does what I was looking for :)

**Comment by phax** [comment]
Ok cool :)
