### ISSUE TITLE
Two tables on the same PDF

### ISSUE THREAD

**Issue by mailidpankaj** [phax/ph-pdf-layout#16]
Hi, 

I have created two tables using PLTable and have added them to PLPageSet aPS1 as below:
      aPS1.addElement(aTable);
      aPS1.addElement(aTable2);

Then, finally added them to PageLayoutPDF as below:

final PageLayoutPDF aPageLayout = new PageLayoutPDF().setCompressPDF(true);
aPageLayout.addPageSet(aPS1);

But, the two tables are created in two separate pages in PDF. I want to create both tables in the same page in PDF. Please suggest how can I achieve this. 

I have attached the source file for your reference. 

Thanks.

[PhaxTwoTablesOnSamePage.DOCX](https://github.com/phax/ph-pdf-layout/files/5179594/PhaxTwoTablesOnSamePage.DOCX)

**Comment by mailidpankaj** [comment]
Please change the file extension from .DOCX to .java before opening the file.

Regards,
Pankaj

**Comment by phax** [comment]
Hi @mailidpankaj  can I use your example code and add it to the test suite?
Would you agree that I publish this as part of the library under Apache 2.0 License?

**Comment by mailidpankaj** [comment]
Hi Phax, 

Sure, you can add it to the test suite. Please let me know how can I create two tables in the same page? I should be able to set the margin and position for both tables wherever I want to position them on the same page.

Regards,
Pankaj

**Comment by phax** [comment]
It took some time but it's pretty simple:
change the "margin bottom" of the first table from 500 to something lower as in `.setMargin (50, 40, 25, 200)` and so the final layout contains the tables below each other:
![grafik](https://user-images.githubusercontent.com/196219/92326988-953edc80-f056-11ea-9990-1763a6c78399.png)
hth

**Comment by mailidpankaj** [comment]
Hi,

While I have changed the .setMargin (50, 40, 25, 40) and the final layout contains two tables on the same page, but I am not able to reduce the space between top and down table. Strangely I have tried to set the .setMargin (50, 40, 25, 40) for both the table and but I see the space between two tables is still the same.

![image](https://user-images.githubusercontent.com/23660549/92330554-6001b100-f08d-11ea-800e-18d27bce3d28.png)


Please suggest how can I reduce the space between two tables. Attached is the picture for the reference. 

Regards,
Pankaj

**Comment by phax** [comment]
This is very simple - get rid of any top and bottom margin.
In the example code I am only using "margin left" and it does the trick

**Comment by mailidpankaj** [comment]
Getting rid of any top and bottom margin has removed "all" the space from top and down table.  How can I create little space between two tables?

**Comment by phax** [comment]
A little space is like 5 or 10.
So if you just want this add either "setMarginBottom(10)" to table1 or "setMarginTop(10)" to table2

**Comment by mailidpankaj** [comment]
Thanks, table space worked.
