### ISSUE TITLE
How to correct display Chinese?

### ISSUE THREAD

**Issue by KenteJohn** [phax/ph-pdf-layout#19]
I get some "?" characters when I write a sentense in Chinese. I have tried almost all the fonts, but it didn't work. I hope to get your response as soon as possible，thank you.

**Comment by phax** [comment]
Hi, try selecting a font at https://fonts.google.com/?subset=chinese-simplified - that should give you a quite broad range.

If you find something suitable, I may be able to add it to https://github.com/phax/ph-fonts to have it available in a more suitable way.

hth

**Comment by KenteJohn** [comment]
Thank you for your help, but due to some policy reasons, I can't visit google.com in China. Everything in your project fits me but fonts, I need Chinese support very much and don't want to give it up.

**Comment by KenteJohn** [comment]
Maybe 'Noto Sans HK' can work?

**Comment by phax** [comment]
Hi. It only has "Noto Sans SC":
![grafik](https://user-images.githubusercontent.com/196219/99635346-23194980-2a42-11eb-9c5b-57097ddecb01.png)

If you like, you can paste an example text here and I send you the screenshot.

**Comment by phax** [comment]
My bad. I also found the "Noto Sans HK"

**Comment by phax** [comment]
Glyphs of Noto Sans HK:
![grafik](https://user-images.githubusercontent.com/196219/99635536-6b386c00-2a42-11eb-8ee7-842065fc8eeb.png)

**Comment by KenteJohn** [comment]
Wow, 'Noto Sans SC' is ok.

**Comment by phax** [comment]
Just for comparison, these are the glyphs of "Noto Sans SC":
![grafik](https://user-images.githubusercontent.com/196219/99635740-b2bef800-2a42-11eb-8539-0e4aa9f3e972.png)

**Comment by KenteJohn** [comment]
HK is complex font, SC is simplified font. I want the simplified font.

**Comment by KenteJohn** [comment]
Maybe 'SC' is simplified Chinese, I guess.

**Comment by phax** [comment]
Yes exactly. There is also a version "TC" for "Traditional Chinese"

**Comment by KenteJohn** [comment]
So, I can use this font at some point in the future,  maybe after a few days or months?

**Comment by phax** [comment]
Yes, I am just trying it out in https://github.com/phax/ph-fonts - if it works, I will release 4.1.2 and create an example in here.

Is this is a reasonable test text:
```
他们所有的设备和仪器彷佛都是有生命的。
```
???

**Comment by KenteJohn** [comment]
Yes and thank you for your support.

**Comment by phax** [comment]
Unfortunately it doesn't work. pdfbox has problems with the OTF font. Any conversion tool from OTF to TTF I tried so far failed :(

**Comment by KenteJohn** [comment]
I believe you can resolve this problem. 加油!

**Comment by phax** [comment]
So I found a solution.
Please see the attached PDF examples.
Do they look good for you?

[font-noto-sans-hk.pdf](https://github.com/phax/ph-pdf-layout/files/5565494/font-noto-sans-hk.pdf)
[font-noto-sans-sc.pdf](https://github.com/phax/ph-pdf-layout/files/5565495/font-noto-sans-sc.pdf)

**Comment by KenteJohn** [comment]
I can not see them.  The hyperlinks are invalid.  Could you give me the directory path about your output?

**Comment by KenteJohn** [comment]
oh, I get the path: pdf/pltext/font-noto-sans-sc.pdf. 
Thank you.
