### ISSUE TITLE
There is no vertical center style when I use Chinese font

### ISSUE THREAD

**Issue by KenteJohn** [phax/ph-pdf-layout#20]
When I use Chinese font, there will be a default line break, one line displays two lines.

**Comment by KenteJohn** [comment]
And , there are also differents when I use regualr and bold fonts in Chinese.

**Comment by phax** [comment]
Can please paste a screenshot here of how it is and how you expected it to be? This library is "optimized" for left-to-right and top-to-bottom operations.
hth

**Comment by KenteJohn** [comment]
ok, I will show you when I get home.

**Comment by KenteJohn** [comment]
By the way , I also have another question. 
 When I have many PLTexts in a PLBox, these PLTexts will be huddled together, I dont want this.
 I want: if one PLText reach the line end, then next PLText will be skip to the next line.

**Comment by phax** [comment]
If you want each text to start with a new line, than I recommend you create a "table" like structure - e.g. with a `PLVBox` or even a `PLTable`.

**Comment by KenteJohn** [comment]
I am very busy these days. I am sorry to response to you so late. You will understand when you see the picture.

![image](https://user-images.githubusercontent.com/41132461/100542016-9c0a7380-3282-11eb-8aff-52a553497960.png)

**Comment by phax** [comment]
Using `setLineSpacing(0.5)` helps to create a layout like this:
![grafik](https://user-images.githubusercontent.com/196219/100551418-a461af00-3280-11eb-96b3-d5db5bb5a1ac.png)

**Comment by KenteJohn** [comment]
I have solved this problem. thanks.

**Comment by phax** [comment]
Super. How did you solve it?

**Comment by KenteJohn** [comment]
just `setPaddingTop(-10)`

**Comment by KenteJohn** [comment]
I have another question. How to add a hyperlink with your API, not PDFbox.

**Comment by KenteJohn** [comment]
There should be some methods in `com.helger.pdflayout4.element.text.PLText` to add a hyperlink.

**Comment by phax** [comment]
Yes, that is already requested in #13 - let me see what I can do
