### ISSUE TITLE
Export table as image

### ISSUE THREAD

**Issue by arjitm786** [phax/ph-pdf-layout#22]
Hi @phax 

Is it possible to save a table as an image?

Thanks for the library and your work.
Regards

**Comment by phax** [comment]
May I ask what you are aiming for?
Do you just want nicely layouted tables as an image, or do you want to have the tables included as an image in the PDF?

**Comment by arjitm786** [comment]
Hello and thanks for the reply.

Yes the first, I want a nicely layouted table saved as an image (jpg/png)

**Comment by phax** [comment]
Sorry - can't help with that :/
I think it should be doable, but the effort is not to be underestimated, even though "just" the "rendering" part needs to be updated to draw on an ImageBuffer...

Happy for every PR :)

**Comment by arjitm786** [comment]
No worries,

Thanks for the reply. I'm just a novice so trying to get my project done (which I implemented using Ralf Stuckert's PDFBox-Layout and later found that I cannot draw table on that). 
So here I'm on learning spree and trying to find workaround. If cannot then will need to change the library.

Regards

**Comment by phax** [comment]
Okay cool - good luck :)
Never used the other library, so can't say anything about it. My library focuses on the "simple things" and provides (hopefully) easy means to extend it where necessary.
Closing this issue for now.
