### ISSUE TITLE
Expose PDPageContentStreamExt in PDPageContentStreamWithCache?

### ISSUE THREAD

**Issue by schneidh** [phax/ph-pdf-layout#23]
Would it be possible to provide a getter for PDPageContentStreamExt within PDPageContentStreamWithCache?  There are some methods on PDPageContentStreamExt that I need that are not available on PDPageContentStreamWithCache.  (e.g. clip() and drawForm())  I'm currently using reflection to work around this, but would love to have a proper getter method.

**Comment by phax** [comment]
Will be part of the 6.0.2 release
