### ISSUE TITLE
Adding page number to the footer

### ISSUE THREAD

**Issue by atothakisandor** [phax/ph-pdf-layout#26]
Hello, 

is it possible to add page numbering to the footer?

Thanks,
Sandor

**Comment by phax** [comment]
Yes, that is possible. Please see https://github.com/phax/ph-pdf-layout/blob/master/src/test/java/com/helger/pdflayout/base/PLPageSetTest.java#L184 on how the page numbers can be used.

**Comment by atothakisandor** [comment]
Gr8! Thank you!
