### ISSUE TITLE
PLTableCell.createEmptyCell() with column span?

### ISSUE THREAD

**Issue by fheldt** [phax/ph-pdf-layout#29]
PLTableCell.createEmptyCell() is quite handy but it is currently not possible to define a column span.

How about a variant like PLTableCell.createEmptyCell(int colspan)? 

So instead of writing

``
plTable.addRow(PLTableCell.createEmptyCell(), PLTableCell.createEmptyCell(), PLTableCell.createEmptyCell(), ...)
``

just                      

``
plTable.addRow(PLTableCell.createEmptyCell(3), ...)
``

**Comment by phax** [comment]
That's a quicky - sure :)

**Comment by phax** [comment]
Part of the next 7.0.1 release

**Comment by fheldt** [comment]
Nice and thanks for that but I meant something slightly different:

with `new PLTableCell(new PLText("xyz", font), 5)` I can create a cell spanning over 5 columns which is eg useful to create a summary row.

`PLTableCell.createEmptyCells(5)` creates an array of 5 empty cells (which is of course sometimes also useful)

**Comment by fheldt** [comment]
So why not just adding this:

`@Nonnull
  public static PLTableCell createEmptyCell (int colspan)
  {
    return new PLTableCell (new PLSpacerX (), colspan);
  }`

**Comment by phax** [comment]
@fheldt  you are absolutely right - reduces the amount of objects needed :)
