### ISSUE TITLE
Cut Text like "overflow:hidden" in css

### ISSUE THREAD

**Issue by terrason** [phax/ph-pdf-layout#34]
Hello, 
I need my table cell hide overflow text, like set "overflow:hidden" style in css
Is there any way to do this?

I am now figuring the max words in a cell by:
```java
        // my cell's width is WidthSpec.perc(30)
        double area=0.3*pages.getAvailableWidth() * this.tableCellHeight-(2*Constants.POINTS_PER_MM*Constants.POINTS_PER_MM);
        double areaPerFont=(fontSize + LINE_SPACING*Constants.POINTS_PER_MM)*fontSize;
        this.tableCellWordsLimit=(int)(area / areaPerFont);
```
Unfortunately this is not work, the result tableCellWordsLimit is higher than seen.

**Comment by phax** [comment]
Try setting a "maxWidth" and/or "maxHeight" of an object to reproduce this effect. I try to create an example snippet

**Comment by terrason** [comment]
> Try setting a "maxWidth" and/or "maxHeight" of an object to reproduce this effect. I try to create an example snippet

Thank you for repling. setMaxHeight on Table cell  seams not working
![image](https://github.com/phax/ph-pdf-layout/assets/4081996/3cbd5fa9-18a6-4a38-9d23-7b6d8cd03be0)

**Comment by terrason** [comment]
Yes,  this suits my job.  Wonderful

**Comment by phax** [comment]
Part of the 7.3.1 release
