### ISSUE TITLE
No assertions for pdfs created during tests?

### ISSUE THREAD

**Issue by Lolf1010** [phax/ph-pdf-layout#35]
Hey,
found your library a couple days ago and have been playing with it a bit. Works great.
At work we are currently looking into generating pdf-files that could include tables and came across your library.
Among the few libraries out there, yours seems to be more actively developed / maintained.

I noticed, if i understand the code correctly, that there are no "real" tests for pdf-files that are created during tests.
I only see that the pdf-files are saved but no assertions are performed on it.

If thats not the case then feel free to close this issue.
If it is the case, why and does that mean that you test the pdfs manually?

Thanks

**Comment by phax** [comment]
Thanks, that looks interesting - I will investigate it

**Comment by phax** [comment]
The library was primarily created to look boring business documents like invoices etc. So the library does not provide fancy stuff like inline formatting or the like, and as a one-person show, I don't have the possibility to create huge functionalities in a short time.

This library is definitively stable enough for production usage and is used for more then 10 years in some governmental applications in Austria to render electronic invoices etc. If you like, I can provide you with access to a Slack channel where you can reach me directly. If so, write me an email to the email address you find in the pom.xml.
hth

**Comment by phax** [comment]
Most of the files were identical to the "stored one". However, some file files were different by 1 or 2 pixels. One file contains random content, which was chaged to constant content now. So result is a bit more predictable - thanks for pointing this out!
