### ISSUE TITLE
ClassNotFoundException: com.helger.collection.map.IntObjectMap

### ISSUE THREAD

**Issue by papagei9** [phax/ph-pdf-layout#4]
Since version 5, this error happens. I just included the newest version 5.0.1 in my pom.xml file.
With version 4.0.1, everything works as expected.

> com.helger.pdflayout4.PDFCreationException: Internal error
> 	at com.helger.pdflayout4.PageLayoutPDF.renderTo(PageLayoutPDF.java:321)
> 	at com.helger.pdflayout4.PageLayoutPDF.renderTo(PageLayoutPDF.java:213)
> 	at PHPDF2.test(PHPDF2.java:148)
> 	at PHPDF2.main(PHPDF2.java:37)
> Caused by: java.lang.NoClassDefFoundError: com/helger/collection/map/IntObjectMap
> 	at com.helger.pdflayout4.spec.LoadedFont.<init>(LoadedFont.java:122)
> 	at com.helger.pdflayout4.render.PreparationContextGlobal.getLoadedFont(PreparationContextGlobal.java:75)
> 	at com.helger.pdflayout4.element.text.AbstractPLText.onPrepare(AbstractPLText.java:382)
> 	at com.helger.pdflayout4.base.AbstractPLRenderableObject.prepare(AbstractPLRenderableObject.java:238)
> 	at com.helger.pdflayout4.element.vbox.AbstractPLVBox.onPrepare(AbstractPLVBox.java:518)
> 	at com.helger.pdflayout4.base.AbstractPLRenderableObject.prepare(AbstractPLRenderableObject.java:238)
> 	at com.helger.pdflayout4.element.vbox.AbstractPLVBox.onPrepare(AbstractPLVBox.java:645)
> 	at com.helger.pdflayout4.base.AbstractPLRenderableObject.prepare(AbstractPLRenderableObject.java:238)
> 	at com.helger.pdflayout4.element.hbox.AbstractPLHBox.onPrepare(AbstractPLHBox.java:295)
> 	at com.helger.pdflayout4.base.AbstractPLRenderableObject.prepare(AbstractPLRenderableObject.java:238)
> 	at com.helger.pdflayout4.element.vbox.AbstractPLVBox.onPrepare(AbstractPLVBox.java:474)
> 	at com.helger.pdflayout4.base.AbstractPLRenderableObject.prepare(AbstractPLRenderableObject.java:238)
> 	at com.helger.pdflayout4.element.hbox.AbstractPLHBox.onPrepare(AbstractPLHBox.java:437)
> 	at com.helger.pdflayout4.base.AbstractPLRenderableObject.prepare(AbstractPLRenderableObject.java:238)
> 	at com.helger.pdflayout4.element.hbox.AbstractPLHBox.onPrepare(AbstractPLHBox.java:295)
> 	at com.helger.pdflayout4.base.AbstractPLRenderableObject.prepare(AbstractPLRenderableObject.java:238)
> 	at com.helger.pdflayout4.element.vbox.AbstractPLVBox.onPrepare(AbstractPLVBox.java:474)
> 	at com.helger.pdflayout4.base.AbstractPLRenderableObject.prepare(AbstractPLRenderableObject.java:238)
> 	at com.helger.pdflayout4.base.PLPageSet.prepareAllPages(PLPageSet.java:426)
> 	at com.helger.pdflayout4.PageLayoutPDF.renderTo(PageLayoutPDF.java:280)
> 	... 3 more
> Caused by: java.lang.ClassNotFoundException: com.helger.collection.map.IntObjectMap
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 23 more
> 
> Process finished with exit code 0

**Comment by phax** [comment]
Please ensure to also update ph-commons to 9.0.1 - than you should be good

**Comment by papagei9** [comment]
I did not have ph-commons as explicit dependency - it's a dependency of ph-pdf-layout already.
Including does not solve the problem... I checked the ph-commons-9.0.1.jar from Maven Repository, and there is simply no IntObjectMap in ph-commons.

I had to add ph-collection 9.0.1 to my pom file to get it working.

**Comment by phax** [comment]
Oops - mea culpa. You are right. It was transitively contained via optional `ph-xml`. It will be fixed in v5.0.3
