### ISSUE TITLE
Including external fonts

### ISSUE THREAD

**Issue by papagei9** [phax/ph-pdf-layout#5]
I'm wondering how I can include external fonts. I know how it works with pdfbox directly, but I did not find any solution for ph-pdf-layout.
Normally, the preloaded fonts are good enough, but I need to write fractions like ¾, ½, ¼ etc. inside a text block. Not all of them exist in default fonts, so I need to add FreeSans.

**Comment by phax** [comment]
Hi, please see e.g. https://github.com/phax/ph-pdf-layout/blob/master/src/test/java/com/helger/pdflayout4/element/text/PLTextTest.java#L186 for a test that uses another font. The interface used is very simply can be found in https://github.com/phax/ph-fonts where I assembled a few OpenSource fonts I liked and that have a broad range of characters. hth

**Comment by papagei9** [comment]
Thank you, that's was I searched for!
