### ISSUE TITLE
Does ph-pdf-layout support image overlays?

### ISSUE THREAD

**Issue by groliffe** [phax/ph-pdf-layout#6]
I.e. put a image on the page and then put text over the top?

**Comment by phax** [comment]
In general yes, but it might be a bit tricky.
First add the image, than work with a negative margin.... 
I'll try to come up with an example

**Comment by phax** [comment]
It works with an HBox. My result looks like this:
![grafik](https://user-images.githubusercontent.com/196219/44648090-41697980-a9e0-11e8-9f49-3c99f7e7b139.png)

**Comment by groliffe** [comment]
Many thanks.
